version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432/tcp
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]

  bot:
    build: .
    command: bash -c "python main.py"
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
volumes:
  postgres_data:
